name: lunchnearby_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0-216.1.beta <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^3.0.0-dev.3
  hooks_riverpod: ^3.0.0-dev.3
  intl: ^0.19.0
  riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  supabase_flutter: ^2.6.0

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator:
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - .env

dependency_overrides:
  analyzer: 6.7.0
